palette = "catppuccin_mocha"

# Don't print a new line at the start of the prompt
add_newline = false
# Pipes â•°â”€ â•­â”€
# Powerline symbols Â î‚° î‚± î‚² î‚³ î‚´ î‚µ î‚¶ î‚· î‚¸ î‚¹ î‚º î‚» î‚¼ î‚½ î‚¾ î‚¿ îƒ€ îƒ îƒ‚ îƒƒ îƒ„ îƒ… îƒ† îƒ‡ îƒˆ îƒŠ  îƒŒ îƒ îƒ îƒ îƒ îƒ‘ îƒ” îƒ’ 
# Wedges ğŸ­§ğŸ­’ ğŸ­£ğŸ­§ğŸ­“
# Random noise ğŸ¬–ğŸ¬¥ğŸ¬”ğŸ¬—

format = """
$directory $nix_shell$git_branch$git_commit$git_status$git_state\
$fill \
$python\
$c\
$rust\
$java\
$golang\
$lua 
$character
"""

[fill]
symbol = ' '

[character]
success_symbol = "[â¯](bold fg:green) "
error_symbol = "[â¯](bold fg:red) "

[nix_shell]
format = '[$symbol(\($state$name\))]($style) '
symbol = '[ï‹œ ](#88c8fc)' # there is a flake symbol inside. try to highlight using mouse
pure_msg = '[ï€£ ](subtext0)'
impure_msg = '[ï‹¼ ](subtext0)'

[git_branch]
format = "on [$symbol $branch(:$remote_branch)](fg:teal) "
style = "bg: green"
symbol = "[ó°˜¬](text)"
truncation_length = 6
truncation_symbol = ".."

[git_commit]
format = '[\($hash$tag\)]($style) '
commit_hash_length = 4
tag_symbol = "ï’¶ "

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = "[ğŸ’ PICKING](bold red)"

[git_status]
format = '[$all_status$ahead_behind]($style) '
conflicted = 'ó°˜­'
ahead = '[ï„‚](sky)'
behind = '[ï„ƒ](red)'
stashed = "[î¶• ](subtext0)"
modified = '[ï‚… ](red)'
staged = '[ï‡€ ](green)'
diverged = '[ó°¹º](yellow)'

[line_break]
disabled = false

[directory]
read_only = " ï‘– "
style = "fg:sapphire"
truncation_length = 2
format = '[$path]($style)'

[python]
symbol = "îˆµ "
format = '\[[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)\]'
version_format = 'v${major}.${minor}'

[golang]
symbol = "î˜§ "
style = "bold sapphire"
version_format = 'v${major}.${minor}'
format = '\[[$symbol($version)]($style)\]'
detect_extensions = ['go', 'templ']

[lua]
symbol = "î˜  "
format = '\[[$symbol($version)]($style)\]'
version_format = 'v${major}.${minor}'

[rust]
symbol = "ó±˜— "
version_format = 'v${major}.${minor}'
style = "fg:peach"
format = '\[[$symbol($version)]($style)\]'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
