format = """
$git_branch\
$git_status\
$python\
$nodejs\
$c\
$rust\
$java\
$golang\
$lua\
$directory $fill $battery $time
$os$username $character
"""

[fill]
symbol = ' '

[character]
success_symbol = '[â¯â¯](bold #19d1bc) '
error_symbol = '[âœ—](bold #fc4267) '

[hostname]
ssh_only = false
format = '[$ssh_symbol](bold blue)@[$hostname](bold #42fc70) '
ssh_symbol = ' ğŸŒ '

[os]
format = "[$symbol]($style) "
style = "bold #87c5fa"
disabled = false

[os.symbols]
openSUSE = "ïŒ” "
Gentoo = "ï…¼"

[username]
style_user = '#facd89 bold'
style_root = 'black bold'
format = '[$user]($style)'
disabled = false
show_always = true

[time]
format = '[$time]($style)'
disabled = false
style = '#facd89 bold'

[battery]
full_symbol = 'ó°¹ '
charging_symbol = 'ó°‚„ '

[[battery.display]]
threshold = 15
style = 'bold #fa8989'
discharging_symbol = 'ó°º '

[[battery.display]]
threshold = 25
style = 'bold #fac389'
discharging_symbol = 'ó°¼ '

[[battery.display]]
threshold = 50
style = 'bold #cffa89'
discharging_symbol = 'ó°¾ '

[[battery.display]]
threshold = 75
style = 'bold #89faa3'
discharging_symbol = 'ó°‚€ '

[[battery.display]]
threshold = 100
style = 'bold #89c7fa'
discharging_symbol = 'ó°¹ '

[python]
symbol = "îˆµ "

[golang]
symbol = "î˜§ "

[lua]
symbol = "î˜  "

[rust]
symbol = "î¨ "
